### ISSUE TITLE
如何创建列表格式的文档

### ISSUE THREAD

**Issue by guoyue01** [Zheaoli/yuque-py#1]
我想请问一下 ，如何创建列表格式的文档？
并且把整个Excel放入文档中？

**Comment by Zheaoli** [comment]
@guoyue01 Hello，目前来看，这一部分的功能，可能不太好通过第三方 SDK 来独立完成，你可以用第三方的编辑器编辑好具体的内容后，然后通过 SDK 上传，目前 MWeb 他们貌似就这么做的

**Comment by Zheaoli** [comment]
close the issue
