### ISSUE TITLE
There have a  mistake in the _get_request method of client

### ISSUE THREAD

**Issue by h-dj** [Zheaoli/yuque-py#5]
source
> request_url = f"{request_url}&{urlencode(requests_data)}"

it shoud be 
> request_url = f"{request_url}?{urlencode(requests_data)}"

**Comment by Zheaoli** [comment]
mybad, I'll fix it

**Comment by Zheaoli** [comment]
https://github.com/Zheaoli/yuque-py/pull/6

**Comment by Zheaoli** [comment]
fix ，close the issue
