### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement yuque-py (from versions: none)

### ISSUE THREAD

**Issue by david-zh-cn** [Zheaoli/yuque-py#7]
ERROR: Could not find a version that satisfies the requirement yuque-py (from versions: none)

xxx$ pip -V
pip 20.3.4 from /Users/daiwei/Library/Python/2.7/lib/python/site-packages/pip (python 2.7)
xxx$ pip install yuque-py
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
Defaulting to user installation because normal site-packages is not writeable
ERROR: Could not find a version that satisfies the requirement yuque-py (from versions: none)
ERROR: No matching distribution found for yuque-py

**Comment by david-zh-cn** [comment]
是需要  license="MIT License",
    python_requires=">=3.6",
python到3.6以上的版本吗

**Comment by Zheaoli** [comment]
@david-zh-cn 是的，需要3.6以上版本
